In [15]:
#1
import math
def my_sinh(x):
    return (math.exp(x) - math.exp(-x)) / 2
print(my_sinh(0))
print(my_sinh(1))
print(my_sinh(2))


0.0
1.1752011936438014
3.626860407847019


In [16]:
#2
import numpy as np
def my_checker_board(n: int):
    a = np.zeros((n,n))
    a[::2,::2] = 1
    a[1::2,1::2] = 1
    return a
print(my_checker_board(1),my_checker_board(2))

[[1.]] [[1. 0.]
 [0. 1.]]


In [17]:
#3
def my_triangle(b: float, h: float):
    return 0.5*b*h
print(my_triangle(1, 1),my_triangle(2, 1),my_triangle(12, 5))
#I have done the triangle area this way in the first chapter's assignment itself.

0.5 1.0 30.0


In [21]:
#4
def my_split_matrix(a):
    middle = (a.shape[1]//2) + (a.shape[1]%2)
    a1 = a[:,:middle]
    a2 = a[:,middle:]
    return [a1,a2]
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a1, a2 = my_split_matrix(a)
print(a1,a2)

[[1 2]
 [4 5]
 [7 8]] [[3]
 [6]
 [9]]


In [35]:
#5
from math import pi
print(pi)
def my_cylinder(r, h):
    v = pi*r*r*h
    s = 2*pi*r*r + 2*pi*r*h
    return [s,v]

print(my_cylinder(1,5),my_cylinder(2,4))

3.141592653589793
[37.69911184307752, 15.707963267948966] [75.39822368615503, 50.26548245743669]


In [23]:
#6
def my_n_odds(a):
    return np.sum(np.floor(a) % 2 != 0)

my_n_odds(np.arange(2,100,2))

np.int64(0)

In [24]:
#7
def my_twos(m,n):
    return np.full((m,n),2)
my_twos(3,2)

array([[2, 2],
       [2, 2],
       [2, 2]])

In [28]:
#8
difference = lambda x, y: x-y
difference(400,697)

-297

In [27]:
#9
def add_string(s1: str, s2: str) -> str:
    return s1 + s2
add_string("Programming"," is fun!")

'Programming is fun!'

In [29]:
#10
def fun(a):
    return a

fun()

TypeError: fun() missing 1 required positional argument: 'a'

In [31]:
#11
def greeting(name: str, age: float) -> str:
    return "Hi, my name is " + name + " and I am " + str(age) + " years old."

print(greeting("John",26))
print(greeting("Kate", 19))

Hi, my name is John and I am 26 years old.
Hi, my name is Kate and I am 19 years old.


In [32]:
#12
def my_donut_area(r1,r2):
    return pi*(r2**2 - r1**2)
my_donut_area(np.arange(1,4), np.arange(2,7,2))

array([ 9.42477796, 37.69911184, 84.82300165])

In [33]:
#13
def my_within_tolerance(A,a,tol):
    A = np.array(A)
    return np.where(np.abs(A-a)<tol)[0]
my_within_tolerance([0,1,2,3],1.5,0.75)

array([1, 2])

In [34]:
#14
def bounding_array(A,top,bottom):
    A = np.array(A)
    A[A > top] = top
    A[A < bottom] = bottom
    return A
bounding_array(np.arange(-5,6,1),3,-3)

array([-3, -3, -3, -2, -1,  0,  1,  2,  3,  3,  3])