In [9]:
#1
x=2
y=3
x=None
#none signifies that x no longer makes sense or meaningful.

In [10]:
#2
print(z)
#creates a name error on z.

NameError: name 'z' is not defined

In [14]:
#3
import math
x=10
y=3
u,v,w,z,r,s,p=x+y,x*y,x/y,math.sin(x),8*math.sin(x),5*math.sin(x*y),x**y
print(u,v,w,z,r,s,p)

13 30 3.3333333333333335 -0.5440211108893698 -4.352168887114958 -4.940158120464309 1000


In [15]:
#4
%whos

Variable   Type      Data/Info
------------------------------
math       module    <module 'math' from '/Lib<...>h.cpython-310-darwin.so'>
p          int       1000
r          float     -4.352168887114958
s          float     -4.940158120464309
u          int       13
v          int       30
w          float     3.3333333333333335
x          int       10
y          int       3
z          float     -0.5440211108893698


In [19]:
#5
S="123"
N=float(S)
print(type(S),type(N))

<class 'str'> <class 'float'>


In [22]:
#6
s1="HELLO"
s2="hello"
print(s1==s2)
print(s1.lower()==s2)
print(s2.upper()==s1)

False
True
True


In [25]:
#7
a="Engineering"
b="Book"
print(f'The word "{a}" has {len(a)} letters.')
print(f'The word "{b}" has {len(b)} letters.')

The word "Engineering" has 11 letters.
The word "Book" has 4 letters.


In [27]:
#8
"Python" in "Python is great!"
#checks condition

True

In [28]:
#9
a="Python is great!"
a[10:-1]

'great'

In [31]:
#10
list_a=[1, 8, 9, 15]
list_a.insert(1,2)
list_a.append(4)
list_a

[1, 2, 8, 9, 15, 4]

In [33]:
#11
list_a.sort()
list_a

[1, 2, 4, 8, 9, 15]

In [34]:
#12
list(a)

['P',
 'y',
 't',
 'h',
 'o',
 'n',
 ' ',
 'i',
 's',
 ' ',
 'g',
 'r',
 'e',
 'a',
 't',
 '!']

In [38]:
#13
tuple_a=("One",1)
tuple_a

('One', 1)

In [39]:
#14
tuple_a[1]

1

In [40]:
#15
t=(2,3,2,3,1,2,5)
set(t)

{1, 2, 3, 5}

In [46]:
#16
c=(2,3,2)
d=(1,2,3)
set_a=set(c)
set_b=set(d)
print(set_a.union(set_b))
print(set_a.intersection(set_b))
print(set_a.difference(set_b))

{1, 2, 3}
{2, 3}
set()


In [50]:
#17
my_dict = {"A": "a", "B": "b", "C": "c"}
my_dict.keys()

dict_keys(['A', 'B', 'C'])

In [51]:
#18
"B" in my_dict

True

In [55]:
#19
import numpy as np
import math
x = np.array([1, 4, 3, 2, 9, 4])
y=np.array([2, 3, 4, 1, 2, 3])
u,v,w,z,r,s,p=x+y,x*y,x/y,np.array([ math.sin(a) for a in x]),8*np.array([ math.sin(a) for a in x]),5*np.array([ math.sin(a) for a in x*y]),x**y
print(u,v,w,z,r,s,p)

[ 3  7  7  3 11  7] [ 2 12 12  2 18 12] [0.5        1.33333333 0.75       2.         4.5        1.33333333] [ 0.84147098 -0.7568025   0.14112001  0.90929743  0.41211849 -0.7568025 ] [ 6.73176788 -6.05441996  1.12896006  7.27437941  3.29694788 -6.05441996] [ 4.54648713 -2.68286459 -2.68286459  4.54648713 -3.75493623 -2.68286459] [ 1 64 81  2 81 64]


In [56]:
#20
np.linspace(-10,10,100)

array([-10.        ,  -9.7979798 ,  -9.5959596 ,  -9.39393939,
        -9.19191919,  -8.98989899,  -8.78787879,  -8.58585859,
        -8.38383838,  -8.18181818,  -7.97979798,  -7.77777778,
        -7.57575758,  -7.37373737,  -7.17171717,  -6.96969697,
        -6.76767677,  -6.56565657,  -6.36363636,  -6.16161616,
        -5.95959596,  -5.75757576,  -5.55555556,  -5.35353535,
        -5.15151515,  -4.94949495,  -4.74747475,  -4.54545455,
        -4.34343434,  -4.14141414,  -3.93939394,  -3.73737374,
        -3.53535354,  -3.33333333,  -3.13131313,  -2.92929293,
        -2.72727273,  -2.52525253,  -2.32323232,  -2.12121212,
        -1.91919192,  -1.71717172,  -1.51515152,  -1.31313131,
        -1.11111111,  -0.90909091,  -0.70707071,  -0.50505051,
        -0.3030303 ,  -0.1010101 ,   0.1010101 ,   0.3030303 ,
         0.50505051,   0.70707071,   0.90909091,   1.11111111,
         1.31313131,   1.51515152,   1.71717172,   1.91919192,
         2.12121212,   2.32323232,   2.52525253,   2.72

In [61]:
#21
array_a = np.array([-1, 0, 1, 2, 0, 3])
b = array_a > 0
result_array = array_a[b]
print(result_array)

[1 2 3]


In [62]:
#22
y=np.array([[3,5,3],[2,2,5],[3,8,9]])
y.T

array([[3, 2, 3],
       [5, 2, 8],
       [3, 5, 9]])

In [63]:
#23
zero_array = np.zeros((2, 4)) 
print(zero_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [64]:
#24
zero_array[:, 1] = 1
print(zero_array)

[[0. 1. 0. 0.]
 [0. 1. 0. 0.]]


In [ ]:
#25
%reset